---
name: thriftls
description: |
  thriftls is a Thrift language server. It provides IDE features
  to any LSP-compatible editor.
homepage: https://github.com/joyme123/thrift-ls
licenses:
  - Apache-2.0
languages:
  - Thrift
categories:
  - LSP

source:
  id: pkg:github/joyme123/thrift-ls@v0.0.7
  asset:
    - target: darwin_x64
      file: thriftls-darwin-amd64:thriftls
    - target: darwin_arm64
      file: thriftls-darwin-arm64:thriftls
    - target: win_x64
      file: thriftls-windows-amd64.exe:thriftls.exe
    - target: win_x86
      file: thriftls-windows-386.exe:thriftls.exe
    - target: linux_x86
      file: thriftls-linux-386:thriftls
    - target: linux_x64
      file: thriftls-linux-amd64:thriftls
    - target: linux_arm64
      file: thriftls-linux-arm64:thriftls


bin:
  thriftls: thriftls
